---
author:
  - 'Martin Thurn <mthurn@cpan.org>'
build_requires:
  Encode: 0
  I18N::Charset: 0
  Test::More: 0
  WWW::Search::Test: 2.265
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Search-Yahoo-China
no_index:
  directory:
    - inc
    - t
requires:
  Data::Dumper: 0
  WWW::Search::Yahoo: 0
  perl: 5.004
resources:
  license: http://dev.perl.org/licenses/
version: 1.003
